# filename: config.toml
[webserver]
ports = ["9090"]
contexttimeout = "5s" # timeout for contexts

[userservice]
ports = ["50053"]
storage = "etcd" #either "etcd" or "memory"
etcdcluster = ["http://localhost:2379", "http://localhost:22379", "http://localhost:32379"]

[postservice]
ports = ["50052"]

[authservice]
ports = ["50051"]

[storage]
storage = ["etcd"]
