# filename: config.toml
[webserver]
ports = ["9090"]
contexttimeout = "10s" # timeout for contexts

[userservice]
ports = ["50053"]
storage = "etcd" #either "etcd" or "memory"
etcd = ["http://localhost:2379", "http://localhost:22379", "http://localhost:32379"]

[postservice]
ports = ["50052"]
storage = "etcd" #either "etcd" or "memory"
etcd = ["http://localhost:2379", "http://localhost:22379", "http://localhost:32379"]

[authservice]
ports = ["50051"]
storage = "etcd" #either "etcd" or "memory"
etcd = ["http://localhost:2379", "http://localhost:22379", "http://localhost:32379"] #only used if storage = "etcd"

[storage]
storage = ["etcd"]
