// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authentication

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsAuthenticated struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthenticated) Reset()         { *m = IsAuthenticated{} }
func (m *IsAuthenticated) String() string { return proto.CompactTextString(m) }
func (*IsAuthenticated) ProtoMessage()    {}
func (*IsAuthenticated) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *IsAuthenticated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthenticated.Unmarshal(m, b)
}
func (m *IsAuthenticated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthenticated.Marshal(b, m, deterministic)
}
func (m *IsAuthenticated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthenticated.Merge(m, src)
}
func (m *IsAuthenticated) XXX_Size() int {
	return xxx_messageInfo_IsAuthenticated.Size(m)
}
func (m *IsAuthenticated) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthenticated.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthenticated proto.InternalMessageInfo

func (m *IsAuthenticated) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

type UserCredential struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredential) Reset()         { *m = UserCredential{} }
func (m *UserCredential) String() string { return proto.CompactTextString(m) }
func (*UserCredential) ProtoMessage()    {}
func (*UserCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *UserCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredential.Unmarshal(m, b)
}
func (m *UserCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredential.Marshal(b, m, deterministic)
}
func (m *UserCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredential.Merge(m, src)
}
func (m *UserCredential) XXX_Size() int {
	return xxx_messageInfo_UserCredential.Size(m)
}
func (m *UserCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredential.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredential proto.InternalMessageInfo

func (m *UserCredential) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserCredential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IsAuthenticated)(nil), "authentication.IsAuthenticated")
	proto.RegisterType((*UserCredential)(nil), "authentication.UserCredential")
	proto.RegisterType((*Void)(nil), "authentication.Void")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x03, 0xb1, 0x53, 0xf3, 0x4a, 0x32, 0x93, 0x13,
	0x4b, 0x32, 0xf3, 0xf3, 0x94, 0xcc, 0xb9, 0xf8, 0x3d, 0x8b, 0x1d, 0x11, 0x62, 0xa9, 0x29, 0x42,
	0x2a, 0x5c, 0xbc, 0x89, 0xc8, 0x02, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0xa8, 0x82, 0x4a,
	0x1e, 0x5c, 0x7c, 0xa1, 0xc5, 0xa9, 0x45, 0xce, 0x45, 0xa9, 0x29, 0x20, 0xc1, 0xc4, 0x1c, 0x21,
	0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0xb0, 0x16, 0xce, 0x20, 0x38,
	0x1f, 0x24, 0x57, 0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94, 0x22, 0xc1, 0x04, 0x91, 0x83, 0xf1,
	0x95, 0xd8, 0xb8, 0x58, 0xc2, 0xf2, 0x33, 0x53, 0x8c, 0x36, 0x33, 0x72, 0xf1, 0x39, 0xa2, 0xb8,
	0x4e, 0x28, 0x82, 0x4b, 0xd8, 0x39, 0x23, 0x35, 0x39, 0x1b, 0x4d, 0x58, 0x4e, 0x0f, 0xd5, 0x17,
	0x7a, 0xa8, 0x2e, 0x91, 0x92, 0x47, 0x97, 0x47, 0xf3, 0xa2, 0x12, 0x83, 0x90, 0x3b, 0x17, 0xaf,
	0x63, 0x4a, 0x0a, 0x92, 0xeb, 0x09, 0x99, 0x29, 0x82, 0x2e, 0x0f, 0x72, 0xb3, 0x12, 0x43, 0x12,
	0x1b, 0x38, 0x5c, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x07, 0x72, 0xd7, 0x65, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationClient interface {
	CheckAuthentication(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*IsAuthenticated, error)
	AddCredential(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*Void, error)
}

type authenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationClient(cc grpc.ClientConnInterface) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) CheckAuthentication(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*IsAuthenticated, error) {
	out := new(IsAuthenticated)
	err := c.cc.Invoke(ctx, "/authentication.Authentication/CheckAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) AddCredential(ctx context.Context, in *UserCredential, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/authentication.Authentication/AddCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
type AuthenticationServer interface {
	CheckAuthentication(context.Context, *UserCredential) (*IsAuthenticated, error)
	AddCredential(context.Context, *UserCredential) (*Void, error)
}

// UnimplementedAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (*UnimplementedAuthenticationServer) CheckAuthentication(ctx context.Context, req *UserCredential) (*IsAuthenticated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuthentication not implemented")
}
func (*UnimplementedAuthenticationServer) AddCredential(ctx context.Context, req *UserCredential) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCredential not implemented")
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_CheckAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).CheckAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication.Authentication/CheckAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).CheckAuthentication(ctx, req.(*UserCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_AddCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).AddCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication.Authentication/AddCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).AddCredential(ctx, req.(*UserCredential))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authentication.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAuthentication",
			Handler:    _Authentication_CheckAuthentication_Handler,
		},
		{
			MethodName: "AddCredential",
			Handler:    _Authentication_AddCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
